#line 2 "knot/conf/libknotd_la-cf-lex.c"

#line 4 "knot/conf/libknotd_la-cf-lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cf_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cf_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cf_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void cf_restart (FILE *input_file ,yyscan_t yyscanner );
void cf__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void cf__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void cf_pop_buffer_state (yyscan_t yyscanner );

static void cf_ensure_buffer_stack (yyscan_t yyscanner );
static void cf__load_buffer_state (yyscan_t yyscanner );
static void cf__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER cf__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE cf__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *cf_alloc (yy_size_t ,yyscan_t yyscanner );
void *cf_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void cf_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer cf__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cf_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[492] =
    {   0,
        0,    0,    0,    0,   88,   87,    2,    3,   87,   87,
        3,   82,   68,   68,   83,   82,   87,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   84,
       87,    2,    0,   81,   80,    0,    1,   82,   82,   68,
        0,   82,   67,   66,   66,   82,    0,   71,    0,    0,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   64,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   84,    0,   86,   85,   82,   72,    0,   71,
       71,   71,    0,    0,   82,   58,   82,   51,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   11,   82,   50,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   46,   82,   82,   82,   82,   82,
        0,    0,   71,   71,   71,    0,    0,    0,    0,   70,
       82,   82,   82,   82,   82,   82,   82,   82,   16,   82,
       82,   82,   82,   82,   82,   60,   82,   82,   12,   82,
       82,   82,    8,   82,   45,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   82,   82,   29,   82,
       82,   82,   82,   54,   82,    0,    0,    0,    0,    0,
        0,   82,   48,   82,   82,   59,   82,   82,   63,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   15,   82,    0,    0,   82,   82,   82,   82,
       82,   14,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   61,   82,   82,   82,   82,   31,   82,
       52,   82,   56,   55,   82,   57,    4,   82,   82,   82,

       82,   82,   23,   82,   82,   69,    0,    0,   44,   82,
       47,   82,   82,   82,   82,   82,   82,   82,   65,   82,
       82,   82,   82,   82,   82,   82,   30,   82,   13,   82,
       82,   10,   82,   82,    7,   62,   28,   24,   82,    0,
        0,   82,   82,   82,   82,   73,   74,   82,    6,    5,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   71,    0,   53,   82,
       82,   82,   75,   82,   82,   82,   82,   82,   82,   49,
       82,   82,   26,   82,   82,   82,   82,   82,   82,   39,
       25,   82,    0,   82,   82,   82,   82,   82,   82,   82,

       43,   82,   82,   82,   82,   82,   82,   27,   82,   82,
       36,   82,   82,   82,   17,   82,   82,   76,   77,   78,
       79,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   22,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   40,   41,   82,
       82,   33,   82,   82,   82,   82,   82,   82,   82,   82,
       21,   82,   82,   35,   82,   19,   20,   82,   82,   82,
       82,   82,   82,    9,   37,   38,   18,   82,   82,   82,
       82,   82,   82,   82,   82,   34,   42,   82,   82,   32,
        0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    4,    4,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   16,   18,    4,    1,
        4,    1,    1,    4,   19,   19,   19,   19,   19,   19,
       20,   21,   21,   21,   21,   21,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,    1,   23,    4,   21,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   21,   33,   34,   35,   36,
       37,   38,   21,   39,   40,   41,   42,   43,   44,   45,
       46,   47,    4,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    5,    2,
        2,    1,    1,    5,    5,    5,    5,    5,    5,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[510] =
    {   0,
        0,    0,   46,   50,  725,  726,   54,  726,   55,  721,
        0,    0,   54,  678,  704,   93,  703,   89,  683,   96,
      680,  686,   37,   78,   99,  689,   22,  692,   90,  100,
      101,  113,  111,  676,  102,  117,  110,  685,  676,  148,
      143,  151,  153,  726,  726,  709,  726,    0,  150,  666,
      692,    0,    0,    0,    0,  159,  691,  180,  690,  689,
      679,  671,  170,  668,  678,  662,  661,  661,  665,  661,
      657,  672,  655,  666,  174,  664,  646,  651,  660,  644,
      647,  655,  657,    0,  658,  645,  642,  647,  645,  142,
      650,  174,  639,  654,  650,  648,  636,  650,  634,  633,

      632,  634,  177,  209,  726,  726,  661,    0,  650,  659,
      208,  648,  647,  229,  625,  626,  618,    0,  620,  618,
      635,  618,  620,  628,  613,  647,  627,  611,  615,  616,
      612,  620,  608,  606,  604,    0,  637,  611,  615,  612,
      599,  611,  601,  610,  612,  592,  598,  222,  594,  226,
      596,  607,  591,  589,    0,  592,  594,  619,  597,  259,
      606,    0,  615,    0,  604,  603,  612,  268,  289,  726,
      591,  574,  589,  577,  585,  589,  585,  573,    0,  573,
      569,  602,  572,  566,  564,    0,  566,  597,    0,  575,
      187,  202,    0,  570,    0,  594,  559,  567,  562,  569,

      572,  556,  552,  569,  555,  563,  550,  548,    0,  556,
      555,  558,  229,  222,  577,  576,  565,    0,  574,    0,
      298,  541,    0,  541,  542,    0,  544,  551,    0,  536,
      535,  281,  550,  541,  545,  542,  541,  533,  531,  540,
      538,  519,  530,  529,  534,  522,  519,  520,  517,  518,
      515,  525,  524,  518,  523,  523,  513,  513,  509,  511,
      504,  513,    0,  313,    0,  536,  503,  510,  507,  512,
      532,    0,  506,  510,  505,  500,  493,  505,  508,  224,
      524,  494,  491,    0,  521,  499,  494,  485,    0,  492,
        0,  481,    0,    0,  494,    0,    0,  493,  513,  483,

      488,  477,    0,  475,  481,    0,  506,    0,    0,  477,
        0,  505,  303,  481,  496,  485,  480,  461,    0,  480,
      468,  470,  466,  466,  494,  300,    0,  465,    0,  473,
      459,    0,  458,  464,    0,    0,    0,    0,  467,    0,
      486,  463,  468,  455,  462,    0,    0,  332,    0,    0,
      461,  453,  455,  450,  478,  446,  447,  440,  453,  448,
      447,  471,  449,  436,  439,  467,    0,    0,    0,  437,
      448,  425,    0,  306,  453,  459,  428,  460,  431,    0,
      316,  441,    0,  423,  422,  427,  420,  434,  452,    0,
        0,  418,  434,  410,  430,  427,  440,  437,  438,  439,

        0,  422,  416,  423,  419,  417,  398,    0,  404,  414,
      434,  409,  405,  392,    0,  403,  404,    0,    0,    0,
        0,  403,  393,  397,  398,  393,  396,  397,  391,  387,
      398,  393,  388,  395,  383,  392,    0,  393,  391,  384,
      380,  388,  373,  256,  388,  384,  386,    0,    0,  382,
      370,    0,  363,  384,  367,  365,  358,  372,  370,  374,
        0,  373,  342,    0,  327,    0,    0,  325,  314,  311,
      309,  310,  321,    0,    0,    0,    0,  308,  310,  302,
      299,  297,  291,  290,  263,    0,    0,  237,  209,    0,
      726,  355,  360,  365,  369,  372,  375,  380,  383,  386,

      389,  227,  392,  395,  199,  179,  128,  111,   47
    } ;

static yyconst flex_int16_t yy_def[510] =
    {   0,
      491,    1,  492,  492,  491,  491,  491,  491,  493,  494,
      495,  495,  491,   13,  496,  495,  497,   16,   16,   16,
       16,   16,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  491,
      498,  491,  493,  491,  491,  494,  491,  495,  495,   13,
      496,   16,  495,   16,  495,  495,  496,  491,  497,  499,
       16,  495,  495,  495,   16,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  491,  498,  491,  491,   49,   56,  500,   58,
      491,  501,  499,  491,   16,  495,  495,  495,  495,   16,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      500,  502,  111,  111,  503,  504,  114,  491,  114,  491,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  160,  502,  504,  505,  168,  168,
      168,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  506,  505,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  264,  506,  507,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  508,
      507,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  508,  509,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  509,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
        0,  491,  491,  491,  491,  491,  491,  491,  491,  491,

      491,  491,  491,  491,  491,  491,  491,  491,  491
    } ;

static yyconst flex_int16_t yy_nxt[774] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,   12,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   12,
       12,   17,    6,   18,   16,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   12,   39,   40,   40,  393,
       41,   40,   40,   78,   41,   42,   42,   44,   79,   45,
       48,   49,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   51,   52,   53,   48,   70,   71,   52,   52,   52,
       54,   52,   52,   48,   55,   48,   53,   48,   55,   48,
       48,   48,   48,   55,   48,   48,   48,   48,   56,   48,

       48,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       51,   52,   72,  367,   73,   61,   52,   52,   52,   52,
       52,   52,   62,   65,   63,   74,   81,   66,   83,   82,
      341,   67,   85,   99,   75,   84,   87,   86,   90,   95,
       88,   96,   91,   76,   97,  105,  100,  106,   98,  103,
      103,   92,   42,   42,   89,   44,   93,   45,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  145,  108,  103,  103,
      146,  307,  108,  108,  108,  108,  108,  108,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  111,  112,  130,

      148,  266,  131,  112,  112,  112,  112,  112,  112,  117,
      149,  105,  239,  106,  132,  118,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  164,  165,  241,  240,  216,
      242,  165,  165,  165,  165,  165,  165,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  168,  169,  490,  202,
      262,  170,  169,  169,  169,  169,  169,  169,  203,  205,
      260,  263,  321,  322,  489,  261,  206,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  219,  219,  219,  219,
      219,  219,  219,  219,  219,  220,  221,  457,  488,  458,
      170,  221,  221,  221,  221,  221,  221,  169,  169,  169,

      169,  169,  169,  169,  169,  169,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  274,  397,  487,  486,  398,
      275,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      344,  357,  485,  484,  483,  345,  358,  482,  359,  481,
      360,  373,  374,  375,  480,  376,  404,  405,  479,  478,
      477,  476,  475,  474,  406,    6,    6,    6,    6,    6,
       43,   43,   43,   43,   43,   46,   46,   46,   46,   46,
       48,   48,  473,   48,   57,   57,   57,   59,   59,   59,
      104,  104,  104,  104,  104,  113,  113,  113,  161,  161,
      161,  112,  112,  112,  165,  165,  165,  217,  217,  217,

      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  170,  414,  413,  412,
      411,  410,  409,  408,  407,  403,  402,  401,  400,  399,
      396,  395,  394,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  372,
      371,  370,  369,  368,  366,  365,  364,  363,  362,  361,

      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  343,  342,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  273,  272,  271,  270,  269,  268,
      267,  218,  168,  265,  264,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,

      244,  243,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  218,
      168,  164,  162,  111,  214,  213,  212,  211,  210,  209,
      208,  207,  204,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  166,  111,  162,  111,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  147,
      144,  143,  142,  141,  140,   84,  139,  138,  137,  136,
      135,  134,  133,  129,  128,  127,  126,  125,  124,  123,

      122,  121,  120,  119,  116,  115,  114,   60,  109,   58,
       48,   47,  102,  101,   94,   80,   77,   69,   68,   64,
       60,   58,   48,   47,  491,    5,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491
    } ;

static yyconst flex_int16_t yy_chk[774] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,  509,
        3,    4,    4,   27,    4,    7,    7,    9,   27,    9,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   23,   23,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   24,  508,   24,   18,   16,   16,   16,   16,
       16,   16,   18,   20,   18,   25,   29,   20,   30,   29,
      507,   20,   31,   37,   25,   30,   32,   31,   33,   35,
       32,   35,   33,   25,   36,   41,   37,   41,   36,   40,
       40,   33,   42,   42,   32,   43,   33,   43,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   90,   56,  103,  103,
       90,  506,   56,   56,   56,   56,   56,   56,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   75,

       92,  505,   75,   58,   58,   58,   58,   58,   58,   63,
       92,  104,  191,  104,   75,   63,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  192,  191,  502,
      192,  111,  111,  111,  111,  111,  111,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  489,  148,
      214,  114,  114,  114,  114,  114,  114,  114,  148,  150,
      213,  214,  280,  280,  488,  213,  150,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  444,  485,  444,
      168,  168,  168,  168,  168,  168,  168,  169,  169,  169,

      169,  169,  169,  169,  169,  169,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  232,  374,  484,  483,  374,
      232,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      313,  326,  482,  481,  480,  313,  326,  479,  326,  478,
      326,  348,  348,  348,  473,  348,  381,  381,  472,  471,
      470,  469,  468,  465,  381,  492,  492,  492,  492,  492,
      493,  493,  493,  493,  493,  494,  494,  494,  494,  494,
      495,  495,  463,  495,  496,  496,  496,  497,  497,  497,
      498,  498,  498,  498,  498,  499,  499,  499,  500,  500,
      500,  501,  501,  501,  503,  503,  503,  504,  504,  504,

      462,  460,  459,  458,  457,  456,  455,  454,  453,  451,
      450,  447,  446,  445,  443,  442,  441,  440,  439,  438,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  417,  416,  414,  413,  412,
      411,  410,  409,  407,  406,  405,  404,  403,  402,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  389,  388,
      387,  386,  385,  384,  382,  379,  378,  377,  376,  375,
      372,  371,  370,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  345,
      344,  343,  342,  341,  339,  334,  333,  331,  330,  328,

      325,  324,  323,  322,  321,  320,  318,  317,  316,  315,
      314,  312,  310,  307,  305,  304,  302,  301,  300,  299,
      298,  295,  292,  290,  288,  287,  286,  285,  283,  282,
      281,  279,  278,  277,  276,  275,  274,  273,  271,  270,
      269,  268,  267,  266,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  231,  230,  228,  227,  225,  224,
      222,  219,  217,  216,  215,  212,  211,  210,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,

      196,  194,  190,  188,  187,  185,  184,  183,  182,  181,
      180,  178,  177,  176,  175,  174,  173,  172,  171,  167,
      166,  165,  163,  161,  159,  158,  157,  156,  154,  153,
      152,  151,  149,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  117,  116,  115,  113,  112,  110,  109,  107,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   91,
       89,   88,   87,   86,   85,   83,   82,   81,   80,   79,
       78,   77,   76,   74,   73,   72,   71,   70,   69,   68,

       67,   66,   65,   64,   62,   61,   60,   59,   57,   51,
       50,   46,   39,   38,   34,   28,   26,   22,   21,   19,
       17,   15,   14,   10,    5,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[88] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 1, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "cf-lex.l"
/*  Copyright (C) 2011 CZ.NIC, z.s.p.o. <knot-dns@labs.nic.cz>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*!
 * \file cf-lex.l
 *
 * \author Ondrej Sury <ondrej.sury@nic.cz>
 *
 * \brief Server configuration structures and API.
 *
 * IP address conversions from BIRD, (c) 1998--2000 Martin Mares <mj@ucw.cz>
 */
#line 26 "cf-lex.l"

#include <config.h>
#include <errno.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>

#include "common/sockaddr.h"
#include "knot/conf/conf.h"
#include "knot/conf/includes.h"
#include "knot/conf/extra.h"
#include "common/log.h"
#include "libknotd_la-cf-parse.h" /* Automake generated header. */

/* Imported symbols. */
#define lval (yylval->tok)
extern void cf_error(void *scanner, const char *format, ...);
extern int (*cf_read_hook)(char *buf, size_t nbytes);
void switch_input(const char *str, void *scanner)
{
	cf__scan_string(str,scanner);
}

/* Convert hex to binary. */
static inline char xd(char d) {
	if (d >= '0' && d <= '9') return d - '0';
	if (d >= 'a' && d <= 'f') return d - 'a' + 10;
	if (d >= 'A' && d <= 'F') return d - 'A' + 10;
	return 0;
}
int hex2bin(const char* src, char *dst, size_t len) {
	for (unsigned i = 0; i < len; ++i) {
		dst[i] = (xd(src[i<<1])<<4) + xd(src[(i<<1)+1]);
	}
	return 0;
}

//#define YY_INPUT(buf,result,max) result = cf_read_hook(buf, max);
#define YY_NO_UNPUT

#define YY_NO_INPUT 1

#line 866 "knot/conf/libknotd_la-cf-lex.c"

#define INITIAL 0
#define include 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE conf_extra_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int cf_lex_init (yyscan_t* scanner);

int cf_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cf_lex_destroy (yyscan_t yyscanner );

int cf_get_debug (yyscan_t yyscanner );

void cf_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE cf_get_extra (yyscan_t yyscanner );

void cf_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *cf_get_in (yyscan_t yyscanner );

void cf_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *cf_get_out (yyscan_t yyscanner );

void cf_set_out  (FILE * out_str ,yyscan_t yyscanner );

int cf_get_leng (yyscan_t yyscanner );

char *cf_get_text (yyscan_t yyscanner );

int cf_get_lineno (yyscan_t yyscanner );

void cf_set_lineno (int line_number ,yyscan_t yyscanner );

int cf_get_column  (yyscan_t yyscanner );

void cf_set_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * cf_get_lval (yyscan_t yyscanner );

void cf_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cf_wrap (yyscan_t yyscanner );
#else
extern int cf_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cf_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int cf_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 87 "cf-lex.l"

#line 1107 "knot/conf/libknotd_la-cf-lex.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cf_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		cf__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 492 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 726 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 88 "cf-lex.l"
/* Ignore comments */;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 89 "cf-lex.l"
/* Ignore whitespace */;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 90 "cf-lex.l"
{ return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 91 "cf-lex.l"
{ lval.t = yytext; return SYSTEM; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "cf-lex.l"
{ lval.t = yytext; return IDENTITY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "cf-lex.l"
{ lval.t = yytext; return HOSTNAME; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "cf-lex.l"
{ lval.t = yytext; return SVERSION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "cf-lex.l"
{ lval.t = yytext; return NSID; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "cf-lex.l"
{ lval.t = yytext; return MAX_UDP_PAYLOAD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "cf-lex.l"
{ lval.t = yytext; return STORAGE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "cf-lex.l"
{ lval.t = yytext; return KEY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "cf-lex.l"
{ lval.t = yytext; return KEYS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "cf-lex.l"
{ lval.t = yytext; return REMOTES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "cf-lex.l"
{ lval.t = yytext; return GROUPS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 103 "cf-lex.l"
{ lval.t = yytext; return ZONES; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 104 "cf-lex.l"
{ lval.t = yytext; return FILENAME; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 105 "cf-lex.l"
{ lval.t = yytext; return DISABLE_ANY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 106 "cf-lex.l"
{ lval.t = yytext; return SEMANTIC_CHECKS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 107 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_RETRIES; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 108 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_TIMEOUT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 109 "cf-lex.l"
{ lval.t = yytext; return DBSYNC_TIMEOUT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "cf-lex.l"
{ lval.t = yytext; return IXFR_FSLIMIT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "cf-lex.l"
{ lval.t = yytext; return XFR_IN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "cf-lex.l"
{ lval.t = yytext; return XFR_OUT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "cf-lex.l"
{ lval.t = yytext; return UPDATE_IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_IN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "cf-lex.l"
{ lval.t = yytext; return NOTIFY_OUT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "cf-lex.l"
{ lval.t = yytext; return WORKERS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "cf-lex.l"
{ lval.t = yytext; return USER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "cf-lex.l"
{ lval.t = yytext; return PIDFILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "cf-lex.l"
{ lval.t = yytext; return RUNDIR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "cf-lex.l"
{ lval.t = yytext; return BUILD_DIFFS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_IDLE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 122 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_HS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 123 "cf-lex.l"
{ lval.t = yytext; return MAX_CONN_REPLY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 124 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 125 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SIZE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 126 "cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SLIP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 127 "cf-lex.l"
{ lval.t = yytext; return TRANSFERS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 128 "cf-lex.l"
{ lval.t = yytext; return DNSSEC_ENABLE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 129 "cf-lex.l"
{ lval.t = yytext; return DNSSEC_KEYDIR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 130 "cf-lex.l"
{ lval.t = yytext; return SIGNATURE_LIFETIME; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "cf-lex.l"
{ lval.t = yytext; return INTERFACES; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "cf-lex.l"
{ lval.t = yytext; return ADDRESS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "cf-lex.l"
{ lval.t = yytext; return PORT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "cf-lex.l"
{ lval.t = yytext; return VIA; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 137 "cf-lex.l"
{ lval.t = yytext; return CONTROL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "cf-lex.l"
{ lval.t = yytext; return ALLOW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "cf-lex.l"
{ lval.t = yytext; return LISTEN_ON; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "cf-lex.l"
{ lval.t = yytext; return LOG; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_ANY; return LOG_SRC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_SERVER; return LOG_SRC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_ANSWER; return LOG_SRC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_ZONE; return LOG_SRC; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_STDOUT; return LOG_DEST; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_STDERR; return LOG_DEST; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_SYSLOG; return LOG_DEST; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_DEBUG); return LOG_LEVEL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_MASK(LOG_DEBUG); return LOG_LEVEL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_MASK(LOG_INFO); return LOG_LEVEL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 153 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_MASK(LOG_NOTICE); return LOG_LEVEL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 154 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_MASK(LOG_WARNING); return LOG_LEVEL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 155 "cf-lex.l"
{ lval.t = yytext; lval.i = LOG_MASK(LOG_ERR); return LOG_LEVEL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 157 "cf-lex.l"
{
  lval.t = yytext;
  lval.i = 0;
  if (strcmp(yytext, "on") == 0) {
    lval.i = 1;
  }
  return BOOL;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "cf-lex.l"
BEGIN(include);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 168 "cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atoi(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "interval must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'm': lval.i *= 60; break; /* minutes */
  case 'h': lval.i *= 60*60; break; /* hours */
  case 'd': lval.i *= 24*60*60; break; /* days */
  case 's': /* seconds */
  default: break;
  }

  return INTERVAL;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 190 "cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atol(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "size must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'k': lval.l = lval.i * 1024; break; /* kB */
  case 'M': lval.l = lval.i * 1024*1024; break; /* MB */
  case 'G': lval.l = lval.i * 1024*1024*1024; break; /* GB */
  default: break;
  }

  return SIZE;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 211 "cf-lex.l"
{
  lval.i = atol(yytext);
  return NUM;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 216 "cf-lex.l"
{
  unsigned char buf[sizeof(struct in_addr)];
  if (inet_pton(AF_INET, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA;
  }
  cf_error(yyscanner, "Invalid IP address.");
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 225 "cf-lex.l"
{
#ifdef DISABLE_IPV6
  lval.t = strdup(yytext);
  cf_error(yyscanner, "IPv6 address support not compiled.");
  return TEXT;
#else
  unsigned char buf[sizeof(struct in6_addr)];
  yytext[strlen(yytext)-1] = '\0';
  if (inet_pton(AF_INET6, yytext+1, buf)) {
	  lval.t = strdup(yytext+1);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
#endif
  }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 241 "cf-lex.l"
{
#ifdef DISABLE_IPV6
	lval.t = strdup(yytext);
	cf_error(yyscanner, "IPv6 address support not compiled.");
	return TEXT;
#else
  unsigned char buf[sizeof(struct in6_addr)];
  if (inet_pton(AF_INET6, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
#endif
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 256 "cf-lex.l"
{
  lval.t = NULL;
  lval.l = 0;
  yytext = yytext + 2; /* Cut off 0x */
  size_t dlen = strlen(yytext);
  if (dlen % 2 == 1) {
    cf_error(yyscanner, "Invalid hex-string length.");
  } else {
    dlen = dlen / 2;
    lval.t = malloc((dlen) * sizeof(char));
    if (lval.t == NULL) {
      cf_error(yyscanner, "Out of memory when allocating hex-string.\n");
    } else {
       memset(lval.t, 0, dlen);
       if (hex2bin(yytext, lval.t, dlen) < 0) {
         cf_error(yyscanner, "Failed to convert hex-string to binary.\n");
       } else {
         lval.l = dlen;
       }
    }
  }

  return HEXSTR;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 281 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_GSS_TSIG;    return TSIG_ALGO_NAME; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 282 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_MD5;    return TSIG_ALGO_NAME; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 283 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA1;   return TSIG_ALGO_NAME; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 284 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA224; return TSIG_ALGO_NAME; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 285 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA256; return TSIG_ALGO_NAME; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 286 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA384; return TSIG_ALGO_NAME; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 287 "cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA512; return TSIG_ALGO_NAME; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 289 "cf-lex.l"
{
  yytext[yyleng-1] = 0;
  lval.t = strdup(yytext + 1);
  return TEXT;
}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 295 "cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 297 "cf-lex.l"
{
  lval.t = strdup(yytext);
  return TEXT /* Last resort, alphanumeric word. */;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 302 "cf-lex.l"
/* Optional : in assignments. */;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include):
#line 304 "cf-lex.l"
{
	conf_include_t *inc = conf_includes_pop(yyextra->includes);
	free(inc->filename);
	if (inc->handle) {
		fclose(inc->handle);
	}

	cf_pop_buffer_state(yyscanner);

	if (!YY_CURRENT_BUFFER) {
		return END;
	}
}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 318 "cf-lex.l"

	YY_BREAK
case 85:
YY_RULE_SETUP
#line 319 "cf-lex.l"
{
	BEGIN(INITIAL);

	// silently skip includes if there was a former error
	if (yyextra->error) {
		return END;
	}

	// remove quotes
	yytext += 1;
	yyleng -= 2;
	yytext[yyleng] = '\0';

	if (!conf_includes_push(yyextra->includes, yytext)) {
		cf_error(yyscanner, "includes nested too deeply");
		return END;
	}

	// retrieved relative to previous config
	conf_include_t *inc = conf_includes_top(yyextra->includes);

	FILE *included = fopen(inc->filename, "r");
	if (!included) {
		cf_error(yyscanner, "cannot open file '%s'", inc->filename);
		conf_includes_pop(yyextra->includes);
		free(inc->filename);
		return END;
	}

	inc->handle = included;
	YY_BUFFER_STATE bs = cf__create_buffer(included,YY_BUF_SIZE,yyscanner);
	cf_push_buffer_state(bs,yyscanner);
}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 353 "cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 355 "cf-lex.l"
ECHO;
	YY_BREAK
#line 1806 "knot/conf/libknotd_la-cf-lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * cf_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( cf_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cf_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cf_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cf_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cf_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 492 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 492 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 491);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cf_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cf_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cf_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        cf_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	cf__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	cf__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void cf__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cf_pop_buffer_state();
	 *		cf_push_buffer_state(new_buffer);
     */
	cf_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cf__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (cf_wrap()) processing, but the only time this flag
	 * is looked at is after cf_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void cf__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cf__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cf_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cf__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cf__create_buffer()
 * @param yyscanner The scanner object.
 */
    void cf__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cf_free((void *) b->yy_ch_buf ,yyscanner );

	cf_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cf_restart() or at EOF.
 */
    static void cf__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	cf__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cf__init_buffer was _probably_
     * called from cf_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void cf__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cf__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	cf_ensure_buffer_stack(yyscanner);

	/* This block is copied from cf__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cf__switch_to_buffer. */
	cf__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void cf_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		cf__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cf_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cf__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cf__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cf_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cf__scan_bytes() instead.
 */
YY_BUFFER_STATE cf__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return cf__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to cf_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cf__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cf_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cf__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cf__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE cf_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int cf_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int cf_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int cf_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *cf_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void cf_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cf_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "cf_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see cf__switch_to_buffer
 */
void cf_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void cf_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int cf_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void cf_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * cf_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void cf_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* cf_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int cf_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* cf_lex_init_extra has the same functionality as cf_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to cf_alloc in
 * the yyextra field.
 */

int cf_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    cf_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    cf_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cf_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cf_lex_init()
     */
    return 0;
}

/* cf_lex_destroy is for both reentrant and non-reentrant scanners. */
int cf_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cf_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	cf_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        cf_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cf_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    cf_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cf_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *cf_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cf_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see cf_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 355 "cf-lex.l"



