#line 2 "knot/conf/libknotd_la-cf-lex.c"

#line 4 "knot/conf/libknotd_la-cf-lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cf_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cf_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cf_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void cf_restart (FILE *input_file ,yyscan_t yyscanner );
void cf__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void cf__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void cf_pop_buffer_state (yyscan_t yyscanner );

static void cf_ensure_buffer_stack (yyscan_t yyscanner );
static void cf__load_buffer_state (yyscan_t yyscanner );
static void cf__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER cf__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE cf__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE cf__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *cf_alloc (yy_size_t ,yyscan_t yyscanner );
void *cf_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void cf_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer cf__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cf_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cf_wrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[569] =
    {   0,
        0,    0,    0,    0,   94,   93,    2,    3,   93,   93,
        3,   88,   74,   74,   89,   88,   93,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   90,   93,    2,    0,   87,   86,    0,    1,   88,
       88,   74,    0,   88,   73,   72,   72,   88,    0,   77,
        0,    0,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   70,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   90,
        0,   92,   91,   88,   78,    0,   77,   77,   77,    0,
        0,   88,   68,   88,   55,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   11,   88,   54,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   50,   88,   88,   88,
       88,   91,   88,    0,    0,   77,   77,   77,    0,    0,
        0,    0,   76,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   16,   88,   88,   88,   88,   88,

       88,   88,   63,   88,   88,   12,   88,   88,   88,    8,
       88,   49,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   31,   88,
       88,   88,   88,   58,   88,    0,    0,    0,    0,    0,
        0,   88,   52,   88,   88,   88,   88,   88,   62,   88,
       88,   66,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   15,
       88,    0,    0,   88,   88,   88,   88,   88,   88,   88,

       88,   14,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   64,   88,   88,   88,   88,   88,
       33,   88,   88,   56,   88,   60,   59,   88,   61,    4,
       88,   88,   88,   88,   88,   88,   23,   88,   88,   75,
        0,    0,   48,   88,   88,   88,   51,   88,   88,   88,
       88,   88,   88,   88,   88,   71,   88,   88,   88,   88,
       88,   88,   88,   88,   32,   88,   88,   13,   88,   88,
       88,   10,   88,   88,   88,    7,   65,   28,   24,   88,
        0,    0,   88,   88,   88,   67,   88,   88,   88,   79,
       80,   88,    6,    5,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   69,   88,   88,   77,    0,   57,   88,   88,   88,
       88,   88,   81,   88,   88,   88,   88,   88,   88,   53,
       88,   88,   26,   88,   88,   88,   88,   88,   88,   88,
       88,   42,   25,   88,    0,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   47,   88,   88,   88,   88,   88,
       88,   27,   88,   88,   88,   39,   88,   88,   88,   88,
       88,   88,   17,   88,   88,   82,   83,   84,   85,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   22,   88,

       88,   88,   88,   88,   88,   46,   88,   88,   88,   88,
       88,   88,   88,   43,   44,   88,   88,   36,   88,   88,
       88,   88,   88,   88,   88,   35,   88,   21,   88,   88,
       88,   88,   38,   88,   19,   20,   88,   88,   88,   88,
       88,   88,   88,   88,    9,   40,   41,   18,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   30,
       29,   88,   37,   45,   88,   88,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    4,    4,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   16,   18,   19,    1,
        4,    1,    1,    4,   20,   20,   20,   20,   20,   20,
       21,   22,   22,   22,   22,   22,   21,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       23,    1,   24,    4,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   22,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,    4,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    1,    5,
        2,    2,    1,    1,    2,    5,    5,    5,    5,    5,
        5,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[587] =
    {   0,
        0,    0,   49,   53,  806,  807,   57,  807,   58,  802,
        0,    0,   57,  756,  785,   99,  784,   95,  775,   79,
      102,  758,  765,   38,   83,  105,  768,   23,  771,   96,
      106,  107,  751,  119,  117,  753,  112,  124,  130,  763,
      754,  157,  160,  165,  167,  807,  807,  789,  807,    0,
      164,  743,  772,    0,    0,    0,    0,  173,  771,  196,
      770,  769,  757,  749,   99,  735,  755,  744,  747,  753,
      736,  735,  735,  740,  736,  731,  747,  729,  741,  187,
      739,  720,  725,  735,  718,  721,  730,  732,    0,  733,
      719,  730,  715,  721,  719,  120,  724,  190,  712,  728,

      719,  723,  721,  708,  723,  706,  705,  704,  707,  189,
      191,  807,  725,  735,    0,  724,  733,  223,  722,  721,
      246,  696,  698,  689,    0,  697,  699,  689,  688,  686,
      704,  686,  689,  697,  681,  718,  696,  679,  684,  206,
      682,  690,  677,  675,  673,    0,  709,  681,  685,  682,
      668,  669,  680,  670,  679,  681,  233,  668,  191,  663,
      184,  666,  655,  676,  659,  657,    0,  661,  663,  690,
      666,  807,  271,  677,    0,  686,    0,  675,  674,  683,
      280,  303,  807,  660,  642,  658,  659,  654,  643,  650,
      651,  655,  651,  638,    0,  639,  634,  670,  638,  631,

      629,  643,    0,  630,  664,    0,  640,  277,  167,    0,
      635,    0,  619,  660,  622,  631,  626,  637,  632,  635,
      618,  614,  632,  618,  626,  612,  610,  609,    0,  618,
      617,  620,  287,  292,  641,  640,  629,    0,  638,    0,
      327,  602,    0,  602,  610,  600,  602,  612,    0,  603,
      610,    0,  594,  593,  228,  609,  600,  604,  595,  600,
      599,  591,  589,  598,  596,  576,  588,  598,  586,  591,
      578,  575,  582,  575,  572,  573,  570,  581,  580,  574,
      579,  575,  578,  568,  568,  563,  566,  558,  568,    0,
      336,    0,  593,  557,  565,  556,  558,  560,  569,  564,

      586,    0,  558,  562,  557,  552,  544,  557,  556,  559,
      202,  577,  545,  542,    0,  574,  550,  542,  544,  534,
        0,  542,  568,    0,  529,    0,    0,  543,    0,    0,
      542,  534,  563,  531,  536,  524,    0,  522,  529,    0,
      556,    0,    0,  525,  523,  516,    0,  524,  552,  294,
      526,  543,  530,  525,  505,    0,  515,  524,  512,  514,
      510,  510,  540,  320,    0,  507,  508,    0,  516,  503,
      500,    0,  499,  510,  505,    0,    0,    0,    0,  508,
        0,  529,  504,  497,  496,    0,  507,  494,  501,    0,
        0,  320,    0,    0,  486,  499,  491,  493,  488,  518,

      484,  485,  477,  491,  486,  490,  484,  510,  477,  485,
      471,    0,  475,  505,    0,    0,    0,  472,  481,  471,
      482,  458,    0,  288,  489,  495,  461,  496,  465,    0,
      323,  475,    0,  456,  455,  461,  452,  452,  467,  458,
      486,    0,    0,  449,  467,  445,  482,  439,  460,  457,
      472,  469,  470,  471,    0,  452,  446,  453,  449,  447,
      427,    0,  433,  444,  437,  465,  438,  436,  433,  419,
      424,  419,    0,  429,  430,    0,    0,    0,    0,  429,
      418,  423,  424,  419,  422,  423,  417,  425,  411,  423,
      424,  417,  412,  442,  409,  417,  404,  414,    0,  415,

      413,  406,  402,  410,  394,    0,  267,  410,  388,  405,
      407,  391,  391,    0,    0,  401,  388,    0,  381,  403,
      385,  383,  376,  391,  389,    0,  393,    0,  378,  386,
      390,  386,    0,  389,    0,    0,  387,  376,  372,  370,
      387,  382,  369,  357,    0,    0,    0,    0,  329,  319,
      318,  328,  320,  296,  284,  284,  287,  248,  239,    0,
        0,  240,    0,    0,  217,  203,    0,  807,  365,  370,
      375,  379,  382,  385,  390,  393,  396,  399,  214,  402,
      405,  194,  168,  120,   73,   50
    } ;

static yyconst flex_int16_t yy_def[587] =
    {   0,
      568,    1,  569,  569,  568,  568,  568,  568,  570,  571,
      572,  572,  568,   13,  573,  572,  574,   16,   16,   16,
       16,   16,   16,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  568,  575,  568,  570,  568,  568,  571,  568,  572,
      572,   13,  573,   16,  572,   16,  572,  572,  573,  568,
      574,  576,   16,  572,  572,  572,   16,  572,  572,   16,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,

      572,  572,  572,  572,  572,  572,  572,  572,  572,  568,
      575,  568,  568,   51,   58,  577,   60,  568,  578,  576,
      568,   16,  572,  572,  572,  572,   16,  572,  572,   16,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  568,  572,  577,  579,  118,  118,  580,  581,  121,
      568,  121,  568,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,

      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  173,  579,  581,  582,  181,  181,
      181,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  583,  582,  572,  572,  572,  572,  572,  572,  572,

      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  291,
      583,  584,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      585,  584,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,

      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  585,  586,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  586,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,

      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,  572,  572,  572,
      572,  572,  572,  572,  572,  572,  572,    0,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568
    } ;

static yyconst flex_int16_t yy_nxt[858] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,   12,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    8,   16,
       12,   12,   17,    6,   12,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   12,   41,
       42,   42,  445,   43,   42,   42,   83,   43,   44,   44,
       46,   84,   47,   50,   51,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   53,  415,   54,   55,   50,   75,
       76,   50,   54,   54,   54,   56,   54,   54,   50,   57,
       50,   55,   50,   57,   50,   50,   50,   50,   50,   57,

       50,   50,   50,   50,   58,   50,   50,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   53,   68,   54,   77,
       69,   78,  382,   63,   54,   54,   54,   54,   54,   54,
       64,   70,   65,   79,   86,   71,   88,   66,   87,   72,
       90,  124,   80,   89,   93,   91,   96,  125,   94,  101,
       97,  102,   81,  104,  103,  106,  156,  105,  110,  110,
       98,  157,  112,   95,  113,   99,   44,   44,  107,   46,
      341,   47,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      110,  110,  115,  112,  265,  113,  293,  266,  115,  115,

      115,  115,  115,  115,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  118,  140,  119,  236,  141,  159,  224,
      221,  119,  119,  119,  119,  119,  119,  225,  160,  222,
      142,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      177,  201,  178,  359,  360,  567,  566,  202,  178,  178,
      178,  178,  178,  178,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  181,  304,  182,  218,  565,  564,  183,
      305,  182,  182,  182,  182,  182,  182,  563,  219,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  240,  451,  241,

      523,  452,  524,  183,  263,  241,  241,  241,  241,  241,
      241,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      287,  264,  289,  388,  562,  288,  561,  560,  389,  423,
      424,  425,  559,  426,  290,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  402,  558,  458,  459,  557,  403,  556,
      555,  404,  554,  405,  460,    6,    6,    6,    6,    6,
       45,   45,   45,   45,   45,   48,   48,   48,   48,   48,
       50,   50,  553,   50,   59,   59,   59,   61,   61,   61,
      111,  111,  111,  111,  111,  120,  120,  120,  174,  174,

      174,  119,  119,  119,  178,  178,  178,  237,  237,  237,
      552,  551,  550,  549,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  539,  538,  537,  536,  535,  534,  533,
      532,  531,  530,  529,  528,  527,  526,  525,  522,  521,
      520,  519,  518,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      183,  470,  469,  468,  467,  466,  465,  464,  463,  462,

      461,  457,  456,  455,  454,  453,  450,  449,  448,  447,
      446,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  412,
      422,  421,  420,  419,  418,  417,  416,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  387,  386,
      385,  384,  383,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,

      342,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  238,  181,  292,  291,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      238,  181,  177,  175,  118,  234,  233,  232,  231,  230,

      229,  228,  227,  226,  223,  220,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  179,  118,
      175,  118,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  158,  155,  154,  153,  152,
      151,  150,   89,  149,  148,  147,  146,  145,  144,  143,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  123,  122,  121,   62,  116,   60,
       50,   49,  109,  108,  100,   92,   85,   82,   74,   73,

       67,   62,   60,   50,   49,  568,    5,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568
    } ;

static yyconst flex_int16_t yy_chk[858] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,  586,    3,    4,    4,   28,    4,    7,    7,
        9,   28,    9,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,  585,   13,   13,   13,   24,
       24,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   20,   16,   25,
       20,   25,  584,   18,   16,   16,   16,   16,   16,   16,
       18,   21,   18,   26,   30,   21,   31,   18,   30,   21,
       32,   65,   26,   31,   34,   32,   35,   65,   34,   37,
       35,   37,   26,   38,   37,   39,   96,   38,   42,   42,
       35,   96,   43,   34,   43,   35,   44,   44,   39,   45,
      583,   45,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   58,   58,   58,   58,   58,   58,   58,   58,   58,
      110,  110,   58,  111,  209,  111,  582,  209,   58,   58,

       58,   58,   58,   58,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   80,   60,  579,   80,   98,  161,
      159,   60,   60,   60,   60,   60,   60,  161,   98,  159,
       80,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  140,  118,  311,  311,  566,  565,  140,  118,  118,
      118,  118,  118,  118,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  255,  121,  157,  562,  559,  121,
      255,  121,  121,  121,  121,  121,  121,  558,  157,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  424,  181,

      507,  424,  507,  181,  208,  181,  181,  181,  181,  181,
      181,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      233,  208,  234,  350,  557,  233,  556,  555,  350,  392,
      392,  392,  554,  392,  234,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  364,  553,  431,  431,  552,  364,  551,
      550,  364,  549,  364,  431,  569,  569,  569,  569,  569,
      570,  570,  570,  570,  570,  571,  571,  571,  571,  571,
      572,  572,  544,  572,  573,  573,  573,  574,  574,  574,
      575,  575,  575,  575,  575,  576,  576,  576,  577,  577,

      577,  578,  578,  578,  580,  580,  580,  581,  581,  581,
      543,  542,  541,  540,  539,  538,  537,  534,  532,  531,
      530,  529,  527,  525,  524,  523,  522,  521,  520,  519,
      517,  516,  513,  512,  511,  510,  509,  508,  505,  504,
      503,  502,  501,  500,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  475,  474,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  461,  460,  459,  458,  457,
      456,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  441,  440,  439,  438,  437,  436,  435,  434,

      432,  429,  428,  427,  426,  425,  422,  421,  420,  419,
      418,  414,  413,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      389,  388,  387,  385,  384,  383,  382,  380,  375,  374,
      373,  371,  370,  369,  367,  366,  363,  362,  361,  360,
      359,  358,  357,  355,  354,  353,  352,  351,  349,  348,
      346,  345,  344,  341,  339,  338,  336,  335,  334,  333,
      332,  331,  328,  325,  323,  322,  320,  319,  318,  317,
      316,  314,  313,  312,  310,  309,  308,  307,  306,  305,
      304,  303,  301,  300,  299,  298,  297,  296,  295,  294,

      293,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  254,  253,  251,  250,  248,
      247,  246,  245,  244,  242,  239,  237,  236,  235,  232,
      231,  230,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  211,  207,
      205,  204,  202,  201,  200,  199,  198,  197,  196,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      180,  179,  178,  176,  174,  171,  170,  169,  168,  166,

      165,  164,  163,  162,  160,  158,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  145,  144,  143,  142,
      141,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  124,  123,  122,  120,  119,
      117,  116,  114,  113,  109,  108,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   97,   95,   94,   93,   92,
       91,   90,   88,   87,   86,   85,   84,   83,   82,   81,
       79,   78,   77,   76,   75,   74,   73,   72,   71,   70,
       69,   68,   67,   66,   64,   63,   62,   61,   59,   53,
       52,   48,   41,   40,   36,   33,   29,   27,   23,   22,

       19,   17,   15,   14,   10,    5,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "knot/conf/cf-lex.l"
/*  Copyright (C) 2011 CZ.NIC, z.s.p.o. <knot-dns@labs.nic.cz>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*!
 * \file cf-lex.l
 *
 * \author Ondrej Sury <ondrej.sury@nic.cz>
 *
 * \brief Server configuration structures and API.
 *
 * IP address conversions from BIRD, (c) 1998--2000 Martin Mares <mj@ucw.cz>
 */
#line 26 "knot/conf/cf-lex.l"

#include <config.h>
#include <dirent.h>
#include <errno.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "common-knot/sockaddr.h"
#include "knot/conf/conf.h"
#include "knot/conf/includes.h"
#include "knot/conf/extra.h"
#include "common/log.h"
#include "libknotd_la-cf-parse.h" /* Automake generated header. */

/* Imported symbols. */
#define lval (yylval->tok)
extern void cf_error(void *scanner, const char *format, ...);
extern int (*cf_read_hook)(char *buf, size_t nbytes);
void switch_input(const char *str, void *scanner)
{
	cf__scan_string(str,scanner);
}

/* Convert hex to binary. */
static inline char xd(char d) {
	if (d >= '0' && d <= '9') return d - '0';
	if (d >= 'a' && d <= 'f') return d - 'a' + 10;
	if (d >= 'A' && d <= 'F') return d - 'A' + 10;
	return 0;
}
int hex2bin(const char* src, char *dst, size_t len) {
	for (unsigned i = 0; i < len; ++i) {
		dst[i] = (xd(src[i<<1])<<4) + xd(src[(i<<1)+1]);
	}
	return 0;
}

//#define YY_INPUT(buf,result,max) result = cf_read_hook(buf, max);
#define YY_NO_UNPUT

#define YY_NO_INPUT 1

#line 902 "knot/conf/libknotd_la-cf-lex.c"

#define INITIAL 0
#define include 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE conf_extra_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int cf_lex_init (yyscan_t* scanner);

int cf_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cf_lex_destroy (yyscan_t yyscanner );

int cf_get_debug (yyscan_t yyscanner );

void cf_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE cf_get_extra (yyscan_t yyscanner );

void cf_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *cf_get_in (yyscan_t yyscanner );

void cf_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *cf_get_out (yyscan_t yyscanner );

void cf_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t cf_get_leng (yyscan_t yyscanner );

char *cf_get_text (yyscan_t yyscanner );

int cf_get_lineno (yyscan_t yyscanner );

void cf_set_lineno (int line_number ,yyscan_t yyscanner );

int cf_get_column  (yyscan_t yyscanner );

void cf_set_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * cf_get_lval (yyscan_t yyscanner );

void cf_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cf_wrap (yyscan_t yyscanner );
#else
extern int cf_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cf_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int cf_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 90 "knot/conf/cf-lex.l"

#line 1138 "knot/conf/libknotd_la-cf-lex.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cf_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		cf__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 569 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 807 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 91 "knot/conf/cf-lex.l"
/* Ignore comments */;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 92 "knot/conf/cf-lex.l"
/* Ignore whitespace */;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 93 "knot/conf/cf-lex.l"
{ return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 94 "knot/conf/cf-lex.l"
{ lval.t = yytext; return SYSTEM; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 95 "knot/conf/cf-lex.l"
{ lval.t = yytext; return IDENTITY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 96 "knot/conf/cf-lex.l"
{ lval.t = yytext; return HOSTNAME; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "knot/conf/cf-lex.l"
{ lval.t = yytext; return SVERSION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 98 "knot/conf/cf-lex.l"
{ lval.t = yytext; return NSID; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "knot/conf/cf-lex.l"
{ lval.t = yytext; return MAX_UDP_PAYLOAD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "knot/conf/cf-lex.l"
{ lval.t = yytext; return STORAGE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "knot/conf/cf-lex.l"
{ lval.t = yytext; return KEY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "knot/conf/cf-lex.l"
{ lval.t = yytext; return KEYS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "knot/conf/cf-lex.l"
{ lval.t = yytext; return REMOTES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "knot/conf/cf-lex.l"
{ lval.t = yytext; return GROUPS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "knot/conf/cf-lex.l"
{ lval.t = yytext; return ZONES; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "knot/conf/cf-lex.l"
{ lval.t = yytext; return FILENAME; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "knot/conf/cf-lex.l"
{ lval.t = yytext; return DISABLE_ANY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "knot/conf/cf-lex.l"
{ lval.t = yytext; return SEMANTIC_CHECKS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 110 "knot/conf/cf-lex.l"
{ lval.t = yytext; return NOTIFY_RETRIES; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 111 "knot/conf/cf-lex.l"
{ lval.t = yytext; return NOTIFY_TIMEOUT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 112 "knot/conf/cf-lex.l"
{ lval.t = yytext; return DBSYNC_TIMEOUT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "knot/conf/cf-lex.l"
{ lval.t = yytext; return IXFR_FSLIMIT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "knot/conf/cf-lex.l"
{ lval.t = yytext; return XFR_IN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "knot/conf/cf-lex.l"
{ lval.t = yytext; return XFR_OUT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "knot/conf/cf-lex.l"
{ lval.t = yytext; return UPDATE_IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "knot/conf/cf-lex.l"
{ lval.t = yytext; return NOTIFY_IN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "knot/conf/cf-lex.l"
{ lval.t = yytext; return NOTIFY_OUT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "knot/conf/cf-lex.l"
{ lval.t = yytext; return WORKERS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "knot/conf/cf-lex.l"
{ lval.t = yytext; return BACKGROUND_WORKERS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 121 "knot/conf/cf-lex.l"
{ lval.t = yytext; return ASYNC_START; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 122 "knot/conf/cf-lex.l"
{ lval.t = yytext; return USER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 123 "knot/conf/cf-lex.l"
{ lval.t = yytext; return PIDFILE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 124 "knot/conf/cf-lex.l"
{ lval.t = yytext; return RUNDIR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 125 "knot/conf/cf-lex.l"
{ lval.t = yytext; return BUILD_DIFFS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 126 "knot/conf/cf-lex.l"
{ lval.t = yytext; return SERIAL_POLICY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "knot/conf/cf-lex.l"
{ lval.t = yytext; return MAX_CONN_IDLE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "knot/conf/cf-lex.l"
{ lval.t = yytext; return MAX_CONN_HS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 129 "knot/conf/cf-lex.l"
{ lval.t = yytext; return MAX_CONN_REPLY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "knot/conf/cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "knot/conf/cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SIZE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 132 "knot/conf/cf-lex.l"
{ lval.t = yytext; return RATE_LIMIT_SLIP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 133 "knot/conf/cf-lex.l"
{ lval.t = yytext; return TRANSFERS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 134 "knot/conf/cf-lex.l"
{ lval.t = yytext; return DNSSEC_ENABLE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "knot/conf/cf-lex.l"
{ lval.t = yytext; return DNSSEC_KEYDIR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 136 "knot/conf/cf-lex.l"
{ lval.t = yytext; return SIGNATURE_LIFETIME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 137 "knot/conf/cf-lex.l"
{ lval.t = yytext; return QUERY_MODULE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 139 "knot/conf/cf-lex.l"
{ lval.t = yytext; return INTERFACES; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "knot/conf/cf-lex.l"
{ lval.t = yytext; return ADDRESS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "knot/conf/cf-lex.l"
{ lval.t = yytext; return PORT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "knot/conf/cf-lex.l"
{ lval.t = yytext; return VIA; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 144 "knot/conf/cf-lex.l"
{ lval.t = yytext; return CONTROL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 145 "knot/conf/cf-lex.l"
{ lval.t = yytext; return ALLOW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "knot/conf/cf-lex.l"
{ lval.t = yytext; return LISTEN_ON; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 148 "knot/conf/cf-lex.l"
{ lval.t = yytext; return LOG; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_ANY; return LOG_SRC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 151 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_SERVER; return LOG_SRC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "knot/conf/cf-lex.l"
{
	lval.t = yytext;
	lval.i = LOG_SERVER;
	fprintf(stderr, "Warning: log category 'answering' is no longer "
	                "supported. Using 'server' instead.\n");
	return LOG_SRC;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 159 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_ZONE; return LOG_SRC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 160 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_STDOUT; return LOG_DEST; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 161 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_STDERR; return LOG_DEST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 162 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOGT_SYSLOG; return LOG_DEST; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 163 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_DEBUG); return LOG_LEVEL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 164 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_INFO); return LOG_LEVEL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_NOTICE); return LOG_LEVEL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_WARNING); return LOG_LEVEL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_ERR); return LOG_LEVEL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 168 "knot/conf/cf-lex.l"
{ lval.t = yytext; lval.i = LOG_UPTO(LOG_CRIT); return LOG_LEVEL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "knot/conf/cf-lex.l"
{
	lval.t = yytext;
	lval.i = LOG_UPTO(LOG_INFO);
	fprintf(stderr, "Warning: log severity 'all' is no longer "
	                "supported. Using 'info' instead.\n");
	return LOG_LEVEL;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 177 "knot/conf/cf-lex.l"
{
  lval.t = yytext;
  if (strcmp(yytext, "increment") == 0) {
    lval.i = CONF_SERIAL_INCREMENT;
  } else {
    lval.i = CONF_SERIAL_UNIXTIME;
  }
  return SERIAL_POLICY_VAL;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 187 "knot/conf/cf-lex.l"
{
  lval.t = yytext;
  lval.i = 0;
  if (strcmp(yytext, "on") == 0) {
    lval.i = 1;
  }
  return BOOL;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 196 "knot/conf/cf-lex.l"
BEGIN(include);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 198 "knot/conf/cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atoi(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "interval must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'm': lval.i *= 60; break; /* minutes */
  case 'h': lval.i *= 60*60; break; /* hours */
  case 'd': lval.i *= 24*60*60; break; /* days */
  case 's': /* seconds */
  default: break;
  }

  return INTERVAL;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 220 "knot/conf/cf-lex.l"
{
  size_t mpos = strlen(yytext) - 1;
  char multiplier = yytext[mpos];
  yytext[mpos] = '\0';
  lval.i = atol(yytext);
  if (lval.i < 1) {
	  cf_error(yyscanner, "size must be a positive integer");
	  return END;
  }

  /* Handle multiplier. */
  switch(multiplier) {
  case 'k': lval.l = lval.i * 1024; break; /* kB */
  case 'M': lval.l = lval.i * 1024*1024; break; /* MB */
  case 'G': lval.l = lval.i * 1024*1024*1024; break; /* GB */
  default: break;
  }

  return SIZE;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 241 "knot/conf/cf-lex.l"
{
  lval.i = atol(yytext);
  return NUM;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 246 "knot/conf/cf-lex.l"
{
  unsigned char buf[sizeof(struct in_addr)];
  if (inet_pton(AF_INET, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA;
  }
  cf_error(yyscanner, "Invalid IP address.");
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 255 "knot/conf/cf-lex.l"
{
  unsigned char buf[sizeof(struct in6_addr)];
  yytext[strlen(yytext)-1] = '\0';
  if (inet_pton(AF_INET6, yytext+1, buf)) {
	  lval.t = strdup(yytext+1);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
  }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 265 "knot/conf/cf-lex.l"
{
  unsigned char buf[sizeof(struct in6_addr)];
  if (inet_pton(AF_INET6, yytext, buf)) {
	  lval.t = strdup(yytext);
	  return IPA6;
  }
  cf_error(yyscanner, "Invalid IPv6 address.");
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 274 "knot/conf/cf-lex.l"
{
  lval.t = NULL;
  lval.l = 0;
  yytext = yytext + 2; /* Cut off 0x */
  size_t dlen = strlen(yytext);
  if (dlen % 2 == 1) {
    cf_error(yyscanner, "Invalid hex-string length.");
  } else {
    dlen = dlen / 2;
    lval.t = malloc((dlen) * sizeof(char));
    if (lval.t == NULL) {
      cf_error(yyscanner, "Out of memory when allocating hex-string.\n");
    } else {
       memset(lval.t, 0, dlen);
       if (hex2bin(yytext, lval.t, dlen) < 0) {
         cf_error(yyscanner, "Failed to convert hex-string to binary.\n");
       } else {
         lval.l = dlen;
       }
    }
  }

  return HEXSTR;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 299 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_GSS_TSIG;    return TSIG_ALGO_NAME; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 300 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_MD5;    return TSIG_ALGO_NAME; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 301 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA1;   return TSIG_ALGO_NAME; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 302 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA224; return TSIG_ALGO_NAME; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 303 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA256; return TSIG_ALGO_NAME; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 304 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA384; return TSIG_ALGO_NAME; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 305 "knot/conf/cf-lex.l"
{ lval.alg = KNOT_TSIG_ALG_HMAC_SHA512; return TSIG_ALGO_NAME; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 307 "knot/conf/cf-lex.l"
{
  yytext[yyleng-1] = 0;
  lval.t = strdup(yytext + 1);
  return TEXT;
}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 313 "knot/conf/cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 315 "knot/conf/cf-lex.l"
{
  lval.t = strdup(yytext);
  return TEXT /* Last resort, alphanumeric word. */;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 320 "knot/conf/cf-lex.l"
/* Optional : in assignments. */;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include):
#line 322 "knot/conf/cf-lex.l"
{
	conf_includes_remove(yyextra->includes);

	cf_pop_buffer_state(yyscanner);

	if (!YY_CURRENT_BUFFER) {
		return END;
	}
}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 332 "knot/conf/cf-lex.l"

	YY_BREAK
case 91:
YY_RULE_SETUP
#line 333 "knot/conf/cf-lex.l"
{
	BEGIN(INITIAL);

	// silently skip includes if there was a former error
	if (yyextra->error) {
		return END;
	}

	// remove optional semicolon
	if (yytext[yyleng - 1] == ';') {
		yyleng -= 1;
	}
	// remove quotes
	yytext += 1;
	yyleng -= 2;
	yytext[yyleng] = '\0';

	if (!conf_includes_push(yyextra->includes, yytext)) {
		cf_error(yyscanner, "include loop");
		return END;
	}

	// retrieved relative to previous config
	conf_include_t *inc = conf_includes_top(yyextra->includes);

	FILE *included = fopen(inc->filename, "r");
	if (!included) {
		cf_error(yyscanner, "cannot open file '%s'", inc->filename);
		conf_includes_remove(yyextra->includes);
		return END;
	}
	inc->handle = included;

	struct stat file_stat;
	if (fstat(fileno(included), &file_stat) == -1) {
		cf_error(yyscanner, "cannot stat file '%s'", yytext);
		conf_includes_remove(yyextra->includes);
		return END;
	}

	if (S_ISDIR(file_stat.st_mode)) {
		// Store dirname statically to reduce deallocation.
		char dirname[256] = { 0 };
		int ret = snprintf(dirname, sizeof(dirname), "%s",
		                   inc->filename);
		if (ret <= 0 || ret >= sizeof(dirname)) {
			cf_error(yyscanner, "dir name is too long '%s'",
			         inc->filename);
			return END;
		}

		// Remove include directory from the stack.
		conf_includes_remove(yyextra->includes);

		DIR *dp = opendir(dirname);
		if (dp == NULL) {
			cf_error(yyscanner, "cannot open directory '%s'",
			         dirname);
			return END;
		}

		struct dirent *ep;
		while ((ep = readdir(dp)) != NULL) {
			// Skip names with leading dot.
			if (*ep->d_name == '.') {
				continue;
			}

			char infile[256] = { 0 };
			int ret = snprintf(infile, sizeof(infile), "%s/%s",
			                   dirname, ep->d_name);
			if (ret <= 0 || ret >= sizeof(infile)) {
				cf_error(yyscanner, "cannot open file '%s/%s'",
				         dirname, ep->d_name);
				return END;
			}

			if (!conf_includes_push(yyextra->includes, infile)) {
				cf_error(yyscanner, "include loop");
				return END;
			}

			// retrieved relative to previous config
			conf_include_t *inc = conf_includes_top(yyextra->includes);

			FILE *included = fopen(inc->filename, "r");
			if (!included) {
				cf_error(yyscanner, "cannot open file '%s'",
				         inc->filename);
				conf_includes_remove(yyextra->includes);
				return END;
			}
			inc->handle = included;

			YY_BUFFER_STATE bs = cf__create_buffer(included,YY_BUF_SIZE,yyscanner);
			cf_push_buffer_state(bs,yyscanner);
		}
		(void)closedir(dp);
	} else {
		YY_BUFFER_STATE bs = cf__create_buffer(included,YY_BUF_SIZE,yyscanner);
		cf_push_buffer_state(bs,yyscanner);
	}
}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 439 "knot/conf/cf-lex.l"
cf_error(yyscanner, "Unterminated string.");
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 441 "knot/conf/cf-lex.l"
ECHO;
	YY_BREAK
#line 1941 "knot/conf/libknotd_la-cf-lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * cf_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( cf_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cf_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cf_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cf_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cf_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 569 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 569 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 568);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cf_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cf_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cf_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        cf_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            cf__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	cf__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	cf__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void cf__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cf_pop_buffer_state();
	 *		cf_push_buffer_state(new_buffer);
     */
	cf_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cf__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (cf_wrap()) processing, but the only time this flag
	 * is looked at is after cf_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void cf__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cf__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cf_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cf__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cf__create_buffer()
 * @param yyscanner The scanner object.
 */
    void cf__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cf_free((void *) b->yy_ch_buf ,yyscanner );

	cf_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cf_restart() or at EOF.
 */
    static void cf__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	cf__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cf__init_buffer was _probably_
     * called from cf_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void cf__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cf__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void cf_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	cf_ensure_buffer_stack(yyscanner);

	/* This block is copied from cf__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cf__switch_to_buffer. */
	cf__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void cf_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		cf__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cf_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)cf_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in cf_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cf__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cf_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cf__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cf_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cf__scan_bytes() instead.
 */
YY_BUFFER_STATE cf__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return cf__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to cf_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cf__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cf_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cf__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cf__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cf__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE cf_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int cf_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int cf_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *cf_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t cf_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *cf_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void cf_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "cf_set_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void cf_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "cf_set_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see cf__switch_to_buffer
 */
void cf_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void cf_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int cf_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void cf_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * cf_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void cf_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* cf_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int cf_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* cf_lex_init_extra has the same functionality as cf_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to cf_alloc in
 * the yyextra field.
 */

int cf_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    cf_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) cf_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    cf_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cf_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cf_lex_init()
     */
    return 0;
}

/* cf_lex_destroy is for both reentrant and non-reentrant scanners. */
int cf_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cf__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cf_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	cf_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        cf_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cf_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    cf_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cf_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *cf_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cf_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see cf_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 441 "knot/conf/cf-lex.l"



