#!/bin/sh
set -e

unset_perms() {
    
}

if test "$1" = "purge"; then
    spool=/var/lib/knot
    rm -f $spool/*.db $spool/*.db.crc
    rmdir $spool 2>/dev/null || true

    dpkg-statoverride --remove /var/lib/knot >/dev/null 2>/dev/null || true
    dpkg-statoverride --remove /etc/knot/knot.conf >/dev/null 2>/dev/null || true
    dpkg-statoverride --remove /etc/knot >/dev/null 2>/dev/null || true

    deluser --quiet knot > /dev/null || true
fi

#DEBHELPER#

exit 0
